M48
; DRILL file {KiCad (6.0.10)} date Sat Jan  7 19:04:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-07T19:04:57+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0906
%
G90
G05
T1
X3.7402Y-2.63
X3.7402Y-3.3
X4.88Y-4.1
X5.865Y-2.75
X6.575Y-4.345
T0
M30
